config/routes.rb
Rails.application.routes.draw do
  resources :image_comments
  resources :images
  root 'images#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :posts
#root 'posts#index'  
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="navbar-brand" ><%= link_to "Home",root_path %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left">
        <%= form_tag(images_path, :method => "get", id: "search-form") do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Images", :class => "form-control" %>
            <span class="input-group-addon" style="background: #ffffff">
              <button type="submit" style="border:0;background:transparent">
                  <span class="glyphicon glyphicon-search"></span>
              </button>  
            </span>
          </div>
          
        <% end %>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Upload' ,new_image_path%></li>
        <% if !current_user %>
        <li><%= link_to "Login",new_user_session_path %></li>
        <% else %>
        
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile",edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out",destroy_user_session_path, method: :delete %></li>
            
          </ul>
        </li>
        <% end %>    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<%= tinymce_assets %>
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body style="background-color: rgb(242, 242, 242);">
    <%= render 'layouts/header' %>
    <div class="" style="padding-top: 20px">

      <%= yield %>
    </div>
  </body>
</html>